"""
FastAPI service exposing the VGC RAG multi-agent pipeline (src/graph.py)
over HTTP. Separate from app.py / dashboard/app.py, which remain
Streamlit-based clients of the same underlying src/ modules.

Run locally:
    uvicorn api.main:app --reload --port 8000

Docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from fastapi.concurrency import run_in_threadpool

from src.graph import run_query
from src.retriever import get_db_pool, get_embedding_model
from api.schemas import HealthResponse, QueryRequest, QueryResponse

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("vgc_api")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Preload the embedding model and DB connection pool once, at process
    startup, rather than lazily on the first request."""
    logger.info("Warming up embedding model and DB pool...")
    await run_in_threadpool(get_embedding_model)
    await run_in_threadpool(get_db_pool)
    logger.info("Startup complete.")
    yield
    # ConnectionPool closes its sockets on process exit; nothing to do here.


app = FastAPI(
    title="VGC RAG Agent API",
    description="Multi-agent RAG system for competitive Pokemon VGC questions.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.get("/health", response_model=HealthResponse)
async def health():
    return HealthResponse(status="ok")


@app.post("/query", response_model=QueryResponse)
async def query(request: QueryRequest):
    """Runs a question through the full retrieve -> rerank -> answer ->
    validate LangGraph pipeline and returns a structured result."""
    chat_history = (
        [msg.model_dump() for msg in request.chat_history]
        if request.chat_history
        else None
    )

    try:
        final_state = await run_in_threadpool(run_query, request.query, chat_history)
    except Exception:
        logger.exception("run_query failed for query: %r", request.query)
        raise HTTPException(
            status_code=500, detail="Internal error running the RAG pipeline."
        )

    return QueryResponse.from_final_state(final_state)